version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongo:27017
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

volumes:
  mongo_data:
